{
 "title": "JupyterHub monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Всего зарегистрировано пользователей",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jupyterhub_total_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Активных пользователей за 24 часа",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jupyterhub_active_users{period=\"24h\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Количество активных серверов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jupyterhub_running_servers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Использование памяти контейнером",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image=\"pattern_notebook:v1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Объем используемого дискового пространства",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{image=\"pattern_notebook:v1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Количество строк в тетрадках пользователя",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "notebook_file_line_count", "legendFormat": "{{container}}:{{file}}" }
   ]
  },
  {
   "title": "Размер тетрадок",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "notebook_file_size_bytes ", "legendFormat": "{{container}}:{{file}}" }
   ]
  }
 ]
}