{
 "title": "Postgres monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Работа сервера",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Данные о пользовательских таблицах",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tables_info_size_bytes",
     "legendFormat": "Владелец: {{table_owner}} Таблица: {{table_name}}"
    }
   ]
  },
  {
   "title": "Размер баз данных",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": " Количество живых строк в таблице",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pg_stat_user_tables_n_live_tup", "legendFormat": "{{relname}}" }
   ]
  },
  {
   "title": "Количество мертвых строк в таблице",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pg_stat_user_tables_n_dead_tup", "legendFormat": "{{relname}}" }
   ]
  }
 ]
}